'use strict';
// code: [flag file (ISO country), English name]
const CURRENCIES = {
  UAH: ['ua', 'Ukrainian Hryvnia'],   USD: ['us', 'US Dollar'],
  EUR: ['eu', 'Euro'],                PLN: ['pl', 'Polish Zloty'],
  GBP: ['gb', 'British Pound'],       CHF: ['ch', 'Swiss Franc'],
  CZK: ['cz', 'Czech Koruna'],        HUF: ['hu', 'Hungarian Forint'],
  RON: ['ro', 'Romanian Leu'],        BGN: ['bg', 'Bulgarian Lev'],
  MDL: ['md', 'Moldovan Leu'],        SEK: ['se', 'Swedish Krona'],
  NOK: ['no', 'Norwegian Krone'],     DKK: ['dk', 'Danish Krone'],
  ISK: ['is', 'Icelandic Krona'],     RSD: ['rs', 'Serbian Dinar'],
  TRY: ['tr', 'Turkish Lira'],        GEL: ['ge', 'Georgian Lari'],
  AMD: ['am', 'Armenian Dram'],       AZN: ['az', 'Azerbaijani Manat'],
  KZT: ['kz', 'Kazakhstani Tenge'],   UZS: ['uz', 'Uzbekistani Som'],
  CAD: ['ca', 'Canadian Dollar'],     AUD: ['au', 'Australian Dollar'],
  NZD: ['nz', 'New Zealand Dollar'],  JPY: ['jp', 'Japanese Yen'],
  CNY: ['cn', 'Chinese Yuan'],        HKD: ['hk', 'Hong Kong Dollar'],
  TWD: ['tw', 'Taiwan Dollar'],       KRW: ['kr', 'South Korean Won'],
  SGD: ['sg', 'Singapore Dollar'],    THB: ['th', 'Thai Baht'],
  VND: ['vn', 'Vietnamese Dong'],     IDR: ['id', 'Indonesian Rupiah'],
  MYR: ['my', 'Malaysian Ringgit'],   PHP: ['ph', 'Philippine Peso'],
  INR: ['in', 'Indian Rupee'],        PKR: ['pk', 'Pakistani Rupee'],
  BDT: ['bd', 'Bangladeshi Taka'],    LKR: ['lk', 'Sri Lankan Rupee'],
  ILS: ['il', 'Israeli Shekel'],      AED: ['ae', 'UAE Dirham'],
  SAR: ['sa', 'Saudi Riyal'],         QAR: ['qa', 'Qatari Riyal'],
  EGP: ['eg', 'Egyptian Pound'],      MAD: ['ma', 'Moroccan Dirham'],
  TND: ['tn', 'Tunisian Dinar'],      ZAR: ['za', 'South African Rand'],
  NGN: ['ng', 'Nigerian Naira'],      KES: ['ke', 'Kenyan Shilling'],
  MXN: ['mx', 'Mexican Peso'],        BRL: ['br', 'Brazilian Real'],
  ARS: ['ar', 'Argentine Peso'],      CLP: ['cl', 'Chilean Peso'],
  COP: ['co', 'Colombian Peso'],      PEN: ['pe', 'Peruvian Sol'],
  XAU: [null, 'Gold (troy oz)'],      XAG: [null, 'Silver (troy oz)'],
  BTC: [null, 'Bitcoin'],             ETH: [null, 'Ethereum'],
  USDT:[null, 'Tether'],
};
